# This workflow will build a Java project with Maven, run tests with JaCoCo, and analyze the code with SonarCloud
name: Java CI

# Controls when the workflow will run
on:
  push:
    branches: [ sonarcloud_workflow ]
  pull_request:
    branches: [ sonarcloud_workflow ]

# Environment variables
env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

# Jobs
jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install -B -U

      - name: Run tests with JaCoCo
        run: mvn jacoco:prepare-agent test jacoco:report

      - name: Analyze with SonarCloud
        run: mvn sonar:sonar -Dsonar.host.url=https://sonar.razorpay.com -Dsonar.login=${{ env.SONAR_TOKEN }} -Dsonar.projectKey=razorpay-java -Dsonar.organization=razorpay
