# This workflow will build a Java project with Maven, run tests with JaCoCo, and analyze the code with SonarCloud
name: Java CI

# Controls when the workflow will run
on:
  push:
    branches: [ sonarcloud_workflow ]
  pull_request:
    branches: [ sonarcloud_workflow ]

# Jobs
jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install -B -U

      - name: Run tests with JaCoCo
        run: mvn jacoco:prepare-agent test jacoco:report
      
      - name: Debug Env variable
        run: |
          echo "Host is ${{ secrets.SONARQUBE_HOST }}"
             
      - name: Analyze with SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONAR_HOST:  ${{ secrets.SONARQUBE_HOST }}
        run: |
          mvn sonar:sonar \
          -Dsonar.host.url=${{ env.SONAR_HOST }} \
          -Dsonar.login=${{ env.SONAR_TOKEN }} \
          -Dsonar.projectKey=razorpay-java \
          -Dsonar.organization=razorpay
